services:
  api:
    image: ghcr.io/danny-avila/librechat:latest
    restart: always
    ports:
      - "3080:3080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./images:/app/client/public/images
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - data-mongo:/data/db
    command: mongod --noauth

volumes:
  data-mongo: