import { prisma } from "../prisma";
import { ContextSystem } from "./context-system";
import { SecurityGuard } from "./security-guard";
import { redis } from "../redis/client";

export type ReportType = "PROJECT" | "SPRINT" | "TEAM" | "EXECUTIVE" | "CLIENT";
export type ReportFrequency = "DAILY" | "WEEKLY" | "SPRINT" | "MONTHLY" | "QUARTERLY";
export type DistributionChannel = "DASHBOARD" | "EMAIL" | "CLIENT_PORTAL" | "NOTIFICATION";

export const REPORT_TYPES = [
  { type: "PROJECT", description: "Project progress updates" },
  { type: "SPRINT", description: "Sprint performance" },
  { type: "TEAM", description: "Workload analysis" },
  { type: "EXECUTIVE", description: "High-level summaries" },
  { type: "CLIENT", description: "Deliverables completed" },
];

export const REPORT_GENERATION_PROCESS = [
  "Collect workspace data", "Analyze trends", "Identify risks",
  "Generate insights", "Create formatted report", "Distribute to channels",
];

export const REPORT_ANSWERS = [
  "What happened?", "What changed?", "What is at risk?",
  "What requires attention?", "What should happen next?",
];

export const REPORT_FREQUENCIES: ReportFrequency[] = ["DAILY", "WEEKLY", "SPRINT", "MONTHLY", "QUARTERLY"];
export const REPORT_CHANNELS: DistributionChannel[] = ["DASHBOARD", "EMAIL", "CLIENT_PORTAL", "NOTIFICATION"];

export class ReportingIntelligence {
  public static async generateReport(
    type: ReportType,
    scopeId: string,
    workspaceId: string,
    userId?: string
  ): Promise<string> {
    if (userId) {
      await SecurityGuard.validate({ userId, workspaceId, action: "read", resourceType: "workspace" });
    }

    const { structured, promptString } = await ContextSystem.getActiveContext({ workspaceId, userId });

    const typeDef = REPORT_TYPES.find(t => t.type === type);
    const contents = typeDef?.description || "General metrics";

    const projectMetrics = await this.generateProjectMetrics(structured);
    const riskSection = await this.generateRiskSection(workspaceId);
    const trendSection = await this.generateTrendSection(workspaceId);

    const report = [
      `# ${typeDef?.description || `${type} Report`}`,
      ``,
      `## Context Overview`,
      promptString,
      ``,
      `## Key Metrics`,
      projectMetrics,
      ``,
      `## Risk Assessment`,
      riskSection,
      ``,
      `## Trends & Insights`,
      trendSection,
      ``,
      `## Recommendations`,
      `Based on the current data, the following actions are recommended:`,
      `- Continue monitoring key deliverables`,
      `- Address any overdue items promptly`,
      `- Review resource allocation for upcoming milestones`,
      ``,
      `---`,
      `*Generated by Nova Reporting Intelligence*`,
      `*Report Type: ${type} | Scope: ${scopeId}*`,
    ].join("\n");

    try {
      await redis.set(`report:${workspaceId}:${type}:${scopeId}`, report);
    } catch {
      // cache write failure is non-fatal
    }
    return report;
  }

  public static async scheduleReport(
    type: ReportType,
    frequency: ReportFrequency,
    scopeId: string,
    workspaceId: string,
    userId?: string
  ): Promise<void> {
        await prisma.scheduledReport.upsert({
      where: { workspaceId_type_scopeId: { workspaceId, type, scopeId } },
      create: { workspaceId, type, frequency, scopeId, nextRun: new Date() },
      update: { frequency },
    });
  }

  public static async distribute(
    report: string,
    channels: DistributionChannel[],
    recipients: string[],
    workspaceId?: string,
  ): Promise<void> {
    for (const channel of channels) {
      if (channel === "EMAIL") {
        for (const to of recipients) {
          const { sendEmail } = await import("./services/email");
          await sendEmail(to, "Nova Automated Report", report);
        }
      } else if (channel === "DASHBOARD") {
        try {
          await redis.set(`report:latest:${workspaceId || "global"}`, report, { ex: 86400 * 7 });
        } catch {
          // non-fatal
        }
      } else if (channel === "NOTIFICATION") {
        try {
          const { createNotification } = await import("@/lib/notification-engine");
          for (const userId of recipients) {
            await createNotification(
              userId,
              workspaceId || "",
              "smart_alert",
              "New Report Available",
              "A new automated report has been generated and is ready to view.",
              { deepLink: `/reports` },
            );
          }
        } catch {
          // non-fatal
        }
      }
    }
  }

  private static async generateProjectMetrics(structured: { project?: { name: string; description?: string | null } | null; workspace?: { name: string; plan: string } | null; task?: { title: string; status: string } | null }): Promise<string> {
    const lines: string[] = [];
    if (structured.project) {
      lines.push(`- **Project**: ${structured.project.name}`);
    }
    if (structured.workspace) {
      lines.push(`- **Workspace**: ${structured.workspace.name} (${structured.workspace.plan})`);
    }
    if (structured.task) {
      lines.push(`- **Active Task**: ${structured.task.title} [${structured.task.status}]`);
    }
    lines.push(`- **Generated**: ${new Date().toISOString().split("T")[0]}`);
    return lines.join("\n");
  }

  private static async generateRiskSection(workspaceId: string): Promise<string> {
    const lines: string[] = [];

    try {
      const overdueTasks = await prisma.task.count({
        where: {
          workspaceId,
          status: { notIn: ["done", "completed", "cancelled"] },
          dueDate: { lt: new Date() },
        },
      });

      const blockedTasks = await prisma.task.count({
        where: {
          workspaceId,
          status: "blocked",
        },
      });

      const activeTasks = await prisma.task.count({
        where: {
          workspaceId,
          status: { notIn: ["done", "completed", "cancelled"] },
        },
      });

      if (overdueTasks > 0) {
        lines.push(`- **Schedule Risk**: ${overdueTasks} overdue task(s) require attention`);
      } else {
        lines.push(`- **Schedule Risk**: No overdue tasks detected`);
      }

      if (blockedTasks > 0) {
        lines.push(`- **Blocked Risk**: ${blockedTasks} blocked task(s) need resolution`);
      } else {
        lines.push(`- **Blocked Risk**: No blocked tasks`);
      }

      const riskRatio = activeTasks > 0 ? (overdueTasks + blockedTasks) / activeTasks : 0;
      if (riskRatio > 0.3) {
        lines.push(`- **Overall Risk Level**: HIGH (${Math.round(riskRatio * 100)}% of active tasks at risk)`);
      } else if (riskRatio > 0.1) {
        lines.push(`- **Overall Risk Level**: MEDIUM (${Math.round(riskRatio * 100)}% of active tasks at risk)`);
      } else {
        lines.push(`- **Overall Risk Level**: LOW`);
      }
    } catch {
      lines.push(`- **Risk Assessment**: Unable to compute risk metrics`);
    }

    return lines.join("\n");
  }

  private static async generateTrendSection(workspaceId: string): Promise<string> {
    const lines: string[] = [];

    try {
      const now = new Date();
      const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
      const sixtyDaysAgo = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

      const recentCompleted = await prisma.task.count({
        where: {
          workspaceId,
          status: { in: ["done", "completed"] },
          updatedAt: { gte: thirtyDaysAgo },
        },
      });

      const previousCompleted = await prisma.task.count({
        where: {
          workspaceId,
          status: { in: ["done", "completed"] },
          updatedAt: { gte: sixtyDaysAgo, lt: thirtyDaysAgo },
        },
      });

      if (recentCompleted > previousCompleted) {
        lines.push(`- **Velocity Trend**: IMPROVING (${recentCompleted} vs ${previousCompleted} tasks completed)`);
      } else if (recentCompleted === previousCompleted) {
        lines.push(`- **Velocity Trend**: STABLE (${recentCompleted} tasks completed per period)`);
      } else {
        lines.push(`- **Velocity Trend**: DECLINING (${recentCompleted} vs ${previousCompleted} tasks completed)`);
      }

      const totalTasks = await prisma.task.count({ where: { workspaceId } });
      const completedTasks = await prisma.task.count({
        where: { workspaceId, status: { in: ["done", "completed"] } },
      });
      const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
      lines.push(`- **Completion Rate**: ${completionRate}% (${completedTasks}/${totalTasks} tasks)`);
    } catch {
      lines.push(`- **Trend Analysis**: Unable to compute trend data`);
    }

    return lines.join("\n");
  }

  public static getReportTypes() {
    return REPORT_TYPES;
  }

  public static getReportDefinitions() {
    return { types: REPORT_TYPES, frequencies: REPORT_FREQUENCIES, channels: REPORT_CHANNELS };
  }
}
