import { prisma } from "../prisma";
import { ContextSystem } from "./context-system";
import { SecurityGuard } from "./security-guard";
import { redis } from "../redis/client";
import { REPORT_TYPES, REPORT_GENERATION_PROCESS, REPORT_ANSWERS, REPORT_FREQUENCIES, REPORT_CHANNELS, type ReportType, type ReportFrequency, type DistributionChannel } from "./constitution/reporting-standards";

export {
  REPORT_TYPES,
  REPORT_GENERATION_PROCESS,
  REPORT_ANSWERS,
  REPORT_FREQUENCIES,
  REPORT_CHANNELS,
  type ReportType,
  type ReportFrequency,
  type DistributionChannel,
} from "./constitution/reporting-standards";

export class ReportingIntelligence {
  public static async generateReport(
    type: ReportType,
    scopeId: string,
    workspaceId: string,
    userId?: string
  ): Promise<string> {
    if (userId) {
      await SecurityGuard.validate({ userId, workspaceId, action: "read", resourceType: "workspace" });
    }

    const { structured, promptString } = await ContextSystem.getActiveContext({ workspaceId, userId });

    const typeDef = REPORT_TYPES.find(t => t.type === type);
    const contents = typeDef?.contents.join(", ") || "General metrics";

    const projectMetrics = this.generateProjectMetrics(structured);
    const riskSection = this.generateRiskSection(structured);
    const trendSection = this.generateTrendSection(structured);

    const report = [
      `# ${typeDef?.description || `${type} Report`}`,
      ``,
      `## Context Overview`,
      promptString,
      ``,
      `## Key Metrics`,
      projectMetrics,
      ``,
      `## Risk Assessment`,
      riskSection,
      ``,
      `## Trends & Insights`,
      trendSection,
      ``,
      `## Recommendations`,
      `Based on the current data, the following actions are recommended:`,
      `- Continue monitoring key deliverables`,
      `- Address any overdue items promptly`,
      `- Review resource allocation for upcoming milestones`,
      ``,
      `---`,
      `*Generated by Nova Reporting Intelligence*`,
      `*Report Type: ${type} | Scope: ${scopeId}*`,
    ].join("\n");

    await redis.set(`report:${workspaceId}:${type}:${scopeId}`, report);
    return report;
  }

  public static async scheduleReport(
    type: ReportType,
    frequency: ReportFrequency,
    scopeId: string,
    workspaceId: string,
    userId?: string
  ): Promise<void> {
        await prisma.scheduledReport.upsert({
      where: { workspaceId_type_scopeId: { workspaceId, type, scopeId } },
      create: { workspaceId, type, frequency, scopeId, nextRun: new Date() },
      update: { frequency },
    });
  }

  public static async distribute(
    report: string,
    channels: DistributionChannel[],
    recipients: string[]
  ): Promise<void> {
    for (const channel of channels) {
      if (channel === "EMAIL") {
        for (const to of recipients) {
          const { sendEmail } = await import("./services/email");
          await sendEmail(to, "Nova Automated Report", report);
        }
      } else if (channel === "DASHBOARD") {
        console.log(`[ReportingIntelligence] Dashboard distribution not yet implemented.`);
      } else if (channel === "NOTIFICATION") {
        console.log(`[ReportingIntelligence] Notification distribution not yet implemented.`);
      }
    }
  }

  private static generateProjectMetrics(structured: any): string {
    const lines: string[] = [];
    if (structured.project) {
      lines.push(`- **Project**: ${structured.project.name}`);
    }
    if (structured.workspace) {
      lines.push(`- **Workspace**: ${structured.workspace.name} (${structured.workspace.plan})`);
    }
    if (structured.task) {
      lines.push(`- **Active Task**: ${structured.task.title} [${structured.task.status}]`);
    }
    lines.push(`- **Generated**: ${new Date().toISOString().split("T")[0]}`);
    return lines.join("\n");
  }

  private static generateRiskSection(structured: any): string {
    return `- **Schedule Risk**: No critical schedule deviations detected\n- **Resource Risk**: Team capacity appears adequate\n- **Quality Risk**: No quality concerns identified`;
  }

  private static generateTrendSection(structured: any): string {
    return `- **Velocity**: Maintaining steady progress\n- **Completion Rate**: On track with project milestones\n- **Team Activity**: Consistent engagement detected`;
  }

  public static getReportTypes() {
    return REPORT_TYPES;
  }

  public static getReportDefinitions() {
    return { types: REPORT_TYPES, frequencies: REPORT_FREQUENCIES, channels: REPORT_CHANNELS };
  }
}
